# Generated by Django 3.2.8 on 2022-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('itemType', models.CharField(max_length=100)),
                ('urlImage', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
