# Generated by Django 3.2.8 on 2022-11-22 17:28

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_id', models.IntegerField(verbose_name=builtins.id)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('coverImage', models.CharField(max_length=200)),
                ('horizontalImage', models.CharField(max_length=200)),
                ('needLogin', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
