# Generated by Django 3.2.8 on 2022-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetv',
            name='id',
        ),
        migrations.AlterField(
            model_name='livetv',
            name='_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
