# Generated by Django 3.2.8 on 2022-11-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0002_auto_20221123_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livetv',
            old_name='_id',
            new_name='idTV',
        ),
    ]
