# Generated by Django 3.2.8 on 2022-11-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0003_rename__id_livetv_idtv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livetv',
            old_name='idTV',
            new_name='_id',
        ),
    ]
