# Generated by Django 3.2.8 on 2022-11-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0004_rename_idtv_livetv__id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livetv',
            options={'ordering': ['created', '_id']},
        ),
    ]
