# Generated by Django 3.2.8 on 2022-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livevideo',
            name='_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livevideo',
            name='description',
            field=models.TextField(),
        ),
    ]
