# Generated by Django 3.2.8 on 2022-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_film', '0002_auto_20221124_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefilm',
            name='_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livefilm',
            name='description',
            field=models.TextField(),
        ),
    ]
