# Generated by Django 3.2.8 on 2022-11-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfilm',
            name='model_chaID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list_film.topicfilm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listfilm',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
